name: favourite_pokemon_repository
description: A Dart Repository which manages the favourite pokemon domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  equatable: ^2.0.3
  pokemon_repository:
    path: ../pokemon_repository

dev_dependencies:
  very_good_analysis: ^3.0.2